language: python
cache: pip
dist: xenial
python:
  - "3.7"
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - sleep 10
  - psql -c 'create database db;' -U postgres
install:
  - cat requirements/base.txt | grep "^Django==\|^psycopg2" | xargs pip install
  - pip install -r requirements/ci.txt
  - pip install awscli
script:
  - bandit -r . -ll
  - docker build -t $DOCKER_REPO .
env:
  global:
    ALLOWED_HOSTS: "*"
    CORS_ORIGIN_WHITELIST: "*"
    DATABASE_ENGINE: "postgresql"
    DATABASE_NAME: "db"
    DATABASE_USER: "root"
    DATABASE_PASSWORD: "root"
    DATABASE_HOST: "localhost"
    DATABASE_PORT: "5432"
    DOCKER_REPO: "mediamash/live-admin"
    JWT_ISSUER: buildly
    JWT_PRIVATE_KEY_RSA_LIVE_ADMIN: $'-----BEGIN RSA PRIVATE KEY-----\nMIIBOwIBAAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRBqhqvJu1hKPYn9HYd75c0\ngIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQJAe5z5096oyeqGX6J+RGGx\n11yuDJ7J+0N4tthUHSWWUtgkd19NvmTM/mVLmPCzZHgNUT+aWUKsQ84+jhru/NQD\n0QIhAOHOzFmjxjTAR1jspn6YtJBKQB40tvT6WEvm2mKm0aD7AiEAyRPwXyZf3JT+\nM6Ui0Mubs7Qb/E4g1d/kVL+o/XoZC6cCIQC+nKzPtnooKW+Q1yOslgdGDgeV9/XB\nUlqap+MNh7hJZQIgZNaM+wqhlFtbx8aO2SrioJI4XqVHrjojpaSgOM3cdY0CIQDB\nQ6ckOaDV937acmWuiZhxuG2euNLwNbMldtCV5ADo/g==\n-----END RSA PRIVATE KEY-----'
    JWT_PUBLIC_KEY_RSA_BUILDLY: $'-----BEGIN PUBLIC KEY-----\nMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB\nqhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==\n-----END PUBLIC KEY-----'

deploy:
  provider: script
  script: bash scripts/deploy-aws.sh
  on:
    branch: master
