# Generated by Django 3.2 on 2023-01-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of Product', max_length=255, null=True)),
                ('description', models.CharField(blank=True, help_text='Name of Product', max_length=255, null=True)),
                ('upc_code', models.CharField(blank=True, help_text='Unique Product Code', max_length=255, null=True)),
                ('link', models.CharField(blank=True, help_text='Link to Product', max_length=255, null=True)),
                ('token', models.CharField(blank=True, help_text='Auth Token', max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
    ]
