# Generated by Django 3.2 on 2023-01-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Shopify', 'Shopify'), ('Amazon', 'Amazon')], help_text='Name of Store', max_length=255, null=True)),
                ('link', models.CharField(blank=True, help_text='Link to Store', max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for store', max_length=255, null=True)),
                ('api_password', models.CharField(blank=True, help_text='API Password for Auth', max_length=255, null=True)),
                ('api_token', models.CharField(blank=True, help_text='API Token for Auth', max_length=255, null=True)),
                ('store_name', models.CharField(blank=True, help_text='Name of Store', max_length=255, null=True)),
                ('status', models.CharField(blank=True, help_text='Status of Provider Link', max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc_code',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Extneral or Internal Stream Host', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopprovider'),
        ),
    ]
