# Generated by Django 3.2.16 on 2023-07-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='category', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, help_text='Collection (Fall, Winter etc.)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, help_text='Type of Product', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, help_text='Tags, comma seperated', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, help_text='Vendor or Supplier', max_length=255, null=True),
        ),
    ]
