# Generated by Django 3.2.16 on 2023-03-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimage_alt'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='related_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='shop.Product'),
        ),
    ]
