# Generated by Django 3.2.16 on 2023-07-31 23:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='live_feed_token',
            field=models.FileField(blank=True, help_text='Video Stream Auth Token', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/greglind/Projects/bluecircle/mm-live-admin/media/videos/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='live_feed_url',
            field=models.FileField(blank=True, help_text='Video Stream Feed', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/greglind/Projects/bluecircle/mm-live-admin/media/videos/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload Video', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/greglind/Projects/bluecircle/mm-live-admin/media/videos/'), upload_to=''),
        ),
    ]
