# Generated by Django 3.2 on 2023-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_livestream_live_feed_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='stream_key',
            field=models.CharField(blank=True, help_text='Unique key for streaming', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='stream_region',
            field=models.CharField(blank=True, help_text='Twitch or similar region', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='stream_user_name',
            field=models.CharField(blank=True, help_text='Authorized username from stream account', max_length=255, null=True),
        ),
    ]
