# Generated by Django 3.2 on 2023-01-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('video', '0004_auto_20230124_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time_minutes', models.CharField(blank=True, help_text='When to display product in Video Minutes', max_length=255, null=True)),
                ('run_time_seconds', models.CharField(blank=True, help_text='When to display product in Video Seconds', max_length=255, null=True)),
                ('product', models.ForeignKey(blank=True, help_text='Product to link to Video', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('video', models.ForeignKey(blank=True, help_text='Video', null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
    ]
