# Generated by Django 3.2 on 2023-02-10 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimage_alt'),
        ('video', '0005_videoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='account_secret',
            field=models.CharField(blank=True, help_text='Account Secret, or API Secret', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='account_key',
            field=models.CharField(blank=True, help_text='Account Key or ID, or API KEY', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, choices=[('YouTube', 'YouTube'), ('Twitch', 'Twitch'), ('Facebook', 'Facebook'), ('Internal Premium', 'Amazon'), ('Internal', 'CloudFlare'), ('TikTok', 'TikTok')], help_text='Name of Streaming Provider (YouTube, Twitch etc.)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product to link to Video', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_products', to='shop.product'),
        ),
    ]
