# Generated by Django 3.2 on 2023-02-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimage_alt'),
        ('video', '0006_auto_20230210_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoproduct',
            old_name='run_time_minutes',
            new_name='show_timestamp',
        ),
        migrations.RemoveField(
            model_name='videoproduct',
            name='run_time_seconds',
        ),
        migrations.AddField(
            model_name='video',
            name='related_products',
            field=models.ManyToManyField(related_name='videos', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='videoproduct',
            name='hide_timestamp',
            field=models.CharField(blank=True, help_text='When to hide the product in Video Seconds', max_length=255, null=True),
        ),
    ]
